services:
  activepieces:
    image: activepieces/activepieces:latest
    container_name: activepieces
    ports:
      - "8081:80"
    volumes:
      - ~/.activepieces:/root/.activepieces
    environment:
      AP_QUEUE_MODE: MEMORY
      AP_DB_TYPE: SQLITE3
      AP_DB_PATH: "/root/.activepieces/db.sqlite"
      AP_FRONTEND_URL: "http://localhost:8081"

  ollama:
    build: ./ollama
    container_name: ollama
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"

  ollama-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: ollama-webui
    restart: unless-stopped
    ports:
      - "3001:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - webui-data:/app
    depends_on:
      - ollama

volumes:
  ollama:
  webui-data:
